
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ElHa
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    static Map data = new HashMap();
    List kebutuhan = new ArrayList();

    public UI() {
        initComponents();
        kebutuhan.add(5);
        kebutuhan.add(2);
        kebutuhan.add(1);
        kebutuhan.add(2);
        kebutuhan.add(4);
        kebutuhan.add(5);
        kebutuhan.add(1);
        kebutuhan.add(3);
        //Map data = new HashMap();
        data.put(1, 3);
        data.put(2, 4);
        data.put(3, 5);
        data.put(4, 6);
        data.put(5, 7);
        data.put(6, 8);
        data.put(7, 9);
        data.put(8, 10);

        tampilkan_data(data, kebutuhan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_popsize = new javax.swing.JTextField();
        txt_cr = new javax.swing.JTextField();
        txt_mr = new javax.swing.JTextField();
        txt_generasi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_data = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_populasi_awal = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_kromosom_terbaik = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_fitnes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Optimasi Sisa pada Pemotongan Pipa");

        jLabel2.setText("Jumlah Popsize");

        jLabel3.setText("Crossover Rate");

        jLabel4.setText("Mutation Rate");

        jLabel5.setText("Jumlah Generasi");

        txt_popsize.setText("8");
        txt_popsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_popsizeActionPerformed(evt);
            }
        });

        txt_cr.setText("0.5");
        txt_cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_crActionPerformed(evt);
            }
        });

        txt_mr.setText("0.2");
        txt_mr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mrActionPerformed(evt);
            }
        });

        txt_generasi.setText("8");
        txt_generasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_generasiActionPerformed(evt);
            }
        });

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tbl_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Kode", "Panjang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_data);
        if (tbl_data.getColumnModel().getColumnCount() > 0) {
            tbl_data.getColumnModel().getColumn(0).setResizable(false);
            tbl_data.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel8.setText("Dataset");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mr, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cr, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_popsize, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_generasi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_popsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_cr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_mr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_generasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Optimasi", jPanel1);

        jLabel6.setText("Populasi Awal");

        tbl_populasi_awal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_populasi_awal);

        jLabel7.setText("Kromosom dan Fitnes Terbaik");

        tbl_kromosom_terbaik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_kromosom_terbaik);

        jLabel9.setText("Kromosom Terbaik dan Fitnes pergenerasi");

        tbl_fitnes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbl_fitnes);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Hasil", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_popsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_popsizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_popsizeActionPerformed

    private void txt_crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_crActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_crActionPerformed

    private void txt_mrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mrActionPerformed

    private void txt_generasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_generasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_generasiActionPerformed

    private void tampilkan_data(Map data_panjang, List kebutuhan) {
        Object header[] = {"Kode", "Panjang", "Jumlah kebutuhan"};
        TableColumn colModel, colModel1, colModel2;
        DefaultTableModel data = new DefaultTableModel(null, header);
        tbl_data.setModel(data);
        tbl_data.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tbl_data.setRowHeight(20);
        colModel = tbl_data.getColumnModel().getColumn(0);
        colModel1 = tbl_data.getColumnModel().getColumn(1);
        colModel2 = tbl_data.getColumnModel().getColumn(2);
        for (int j = 0; j < data_panjang.size(); j++) {
            colModel.setPreferredWidth(40);
            colModel1.setPreferredWidth(100);
            colModel2.setPreferredWidth(170);
            String temp = "";
            String kolom0 = String.valueOf(j + 1);
            String kolom1 = String.valueOf(data_panjang.get(j + 1) + " cm");
            String kolom2 = String.valueOf(kebutuhan.get(j));
            String kolom[] = {kolom0, kolom1, kolom2};
            data.addRow(kolom);
        }
    }

    private void tampilkan_populasi_awal(Map populasi_awal) {
        Object header[] = {"No", "Korosom"};

        DefaultTableModel data = new DefaultTableModel(null, header);
        tbl_populasi_awal.setModel(data);
        for (int j = 0; j < populasi_awal.size(); j++) {
            String kolom0 = String.valueOf(j + 1);
            String kolom1 = String.valueOf(populasi_awal.get(j));
            String kolom[] = {kolom0, kolom1};
            data.addRow(kolom);
        }
    }

    private void tampilkan_kromosom_pergenerasi(Map kromosom_pergenerasi, double[] fitnes_pergenerasi, List sisa) {
        Object header[] = {"No", "Korosom", "Jum Bahan", "Sisa perbahan", "Fitnes"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        tbl_fitnes.setModel(data);
        for (int j = 0; j < kromosom_pergenerasi.size(); j++) {
            String kolom0 = String.valueOf(j + 1);
            String kolom1 = String.valueOf(kromosom_pergenerasi.get(j));
            List temp_sisa= (List)sisa.get(j);
            String kolom2 = String.valueOf(temp_sisa.size());
            String kolom3 = String.valueOf(temp_sisa);
            String kolom4 = String.valueOf(fitnes_pergenerasi[j]);
            String kolom[] = {kolom0, kolom1, kolom2, kolom3, kolom4};
            data.addRow(kolom);
        }
    }
    private void tampilkan_kromosom_terbaik(List kromosom, double fitnes, int jum_bahan) {
        Object header[] = {"No", "Korosom", "Fitnes"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        tbl_kromosom_terbaik.setModel(data);
        String kolom0 = String.valueOf(1);
        String kolom1 = String.valueOf(kromosom);
        String kolom2 = String.valueOf(jum_bahan);
        String kolom3 = String.valueOf(fitnes);
        String kolom[] = {kolom0, kolom1, kolom2,kolom3};
        data.addRow(kolom);

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        alev1 optimasi = new alev1();
        int n = data.size();
        int popsize = Integer.valueOf(txt_popsize.getText());
        int generasi = Integer.valueOf(txt_generasi.getText());
        double[] fitnes_pergenerasi = new double[generasi];
        Map kromosom_pergenerasi = new HashMap();
        int bahan = 14;
        Map initial_pop = optimasi.Inisiate_population(popsize, n, data, kebutuhan);
        System.out.println(data);
        tampilkan_populasi_awal(initial_pop);
        List kromosom_terbaik = new ArrayList();
        int jum_bahan=0;
        List sisa_terbaik = new ArrayList();
        double fitnes_terbaik = 1;
        for (int i = 0; i < generasi; i++) {
            Map off_cross = optimasi.crosover_all(initial_pop, Double.valueOf(txt_cr.getText()));
            Map off_mutasi = optimasi.scramble_mutasi(initial_pop, Double.valueOf(txt_mr.getText()));
            List fitnes = optimasi.get_fitnes(initial_pop, off_cross, off_mutasi, data, bahan);
            System.out.println(fitnes);
            int index[] = optimasi.sort(fitnes);
            initial_pop = optimasi.seleksi(initial_pop, off_cross, off_mutasi, index, popsize);
            List temp_sisa_terbaik = optimasi.hitung_bahan((List) initial_pop.get(0), data, bahan);
            sisa_terbaik.add(temp_sisa_terbaik);
            fitnes_pergenerasi[i] = optimasi.hitung_fitnes(temp_sisa_terbaik, bahan);
            kromosom_pergenerasi.put(i, (List) initial_pop.get(0));
            if (fitnes_pergenerasi[i] < fitnes_terbaik) {
                fitnes_terbaik = fitnes_pergenerasi[i];
                kromosom_terbaik = (List) kromosom_pergenerasi.get(i);
                List temp=(List)sisa_terbaik.get(i);
                jum_bahan=temp.size();
            }
        }
        tampilkan_kromosom_pergenerasi(kromosom_pergenerasi, fitnes_pergenerasi, sisa_terbaik);
        tampilkan_kromosom_terbaik(kromosom_terbaik, fitnes_terbaik, jum_bahan);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tbl_data;
    private javax.swing.JTable tbl_fitnes;
    private javax.swing.JTable tbl_kromosom_terbaik;
    private javax.swing.JTable tbl_populasi_awal;
    private javax.swing.JTextField txt_cr;
    private javax.swing.JTextField txt_generasi;
    private javax.swing.JTextField txt_mr;
    private javax.swing.JTextField txt_popsize;
    // End of variables declaration//GEN-END:variables
}
